export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as Service} from "./Service"
export {default as LayOut} from "../LayOut/RootLayout"
export {default as ErrorPage} from "./ErrorPage"